services:
  baby_shower:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      # Persiste el archivo confirmados.txt entre deploys
      - baby_shower_data:/app/server/data
    networks:
      - dokploy-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

volumes:
  baby_shower_data:

networks:
  dokploy-network:
    external: true
